sudo: required
language: python
python:
- "2.7"
- "3.5"

branches:
    only:
    - master
    - develop

install:
- pip install -r requirements.txt

script:
- nosetests ./test
- make -C docs html

notifications:
  slack: bolt-ta:EVxZet7QX82F4aEh21tvrtFc
